- job:
    name: metalsmith-integration-base
    description: |
        Base job for devstack-based metalsmith jobs.
    parent: devstack-minimal
    nodeset: openstack-single-node-focal
    post-run: playbooks/integration/post.yaml
    run: playbooks/integration/run.yaml
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^lower-constraints.txt$
      - ^install-guide/.*$
      - ^ironic/tests/.*$
      - ^metalsmith/test/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^test-requirements.txt$
      - ^tools/.*$
      - ^tox.ini$
    timeout: 5400
    required-projects:
      - openstack/diskimage-builder
      - openstack/keystone
      - openstack/neutron
      - openstack/glance
      - openstack/swift
      - openstack/ironic
      - openstack/ironic-python-agent-builder
      - openstack/metalsmith
    vars:
      ironic_bm_logs: /opt/stack/logs/ironic-bm-logs
      devstack_services:
        dstat: false
        etcd3: true
        mysql: true
        rabbit: true
        tls-proxy: true
        # Keystone services
        key: true
        # Glance services
        g-api: true
        g-reg: true
        # Nova services
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # Neutron services
        q-agt: true
        q-dhcp: true
        q-l3: true
        q-meta: true
        q-metering: true
        q-svc: true
        # OVN services
        ovn-controller: false
        ovn-northd: false
        ovs-vswitchd: false
        ovsdb-server: false
        q-ovn-metadata-agent: false
        # Swift services
        s-account: true
        s-container: true
        s-object: true
        s-proxy: true
        # Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        # Ceilometer services
        ceilometer-acentral: False
        ceilometer-acompute: False
        ceilometer-alarm-evaluator: False
        ceilometer-alarm-notifier: False
        ceilometer-anotification: False
        ceilometer-api: False
        ceilometer-collector: False
        # Services we don't need.
        horizon: false
        tempest: false
      devstack_plugins:
        ironic: https://opendev.org/openstack/ironic
      devstack_localrc:
        Q_AGENT: openvswitch
        Q_ML2_TENANT_NETWORK_TYPE: vxlan
        Q_ML2_PLUGIN_MECHANISM_DRIVERS: openvswitch
        GLANCE_LIMIT_IMAGE_SIZE_TOTAL: 5000
        IRONIC_BAREMETAL_BASIC_OPS: true
        IRONIC_BUILD_DEPLOY_RAMDISK: false
        IRONIC_DEFAULT_DEPLOY_INTERFACE: direct
        IRONIC_DEPLOY_DRIVER: ipmi
        IRONIC_RAMDISK_TYPE: tinyipa
        IRONIC_VM_COUNT: 1
        IRONIC_VM_LOG_DIR: /opt/stack/logs/ironic-bm-logs
        IRONIC_VM_SPECS_CPU: 2
        IRONIC_VM_SPECS_DISK: 10
        IRONIC_VM_SPECS_RAM: 1024
        LIBVIRT_STORAGE_POOL_PATH: /opt/libvirt/images
        SWIFT_ENABLE_TEMPURLS: true
        SWIFT_HASH: 54bd5642300c4b45-846f8636a70a07d2
        SWIFT_START_ALL_SERVICES: false
        SWIFT_TEMPURL_KEY: 54bd5642300c4b45846f8636a70a07d2
      centos_glance_initramds_image: test-centos-initramfs
      centos_glance_kernel_image: test-centos-kernel
      centos_glance_root_image: test-centos-partition
      centos_glance_whole_disk_image: test-centos-wholedisk
      metalsmith_root_size: 9
      metalsmith_python: python3

- job:
    name: metalsmith-integration-glance-localboot-centos8-uefi
    description: |
        Integration job using Glance as image source and CentOS8 with local boot
        and UEFI. Images are built with diskimage-builder.
    parent: metalsmith-integration-base
    timeout: 8200
    run: playbooks/integration/centos8-integration.yaml
    vars:
      devstack_localrc:
        # NOTE(dtantsur): we need to use streaming, otherwise the image won't
        # fit in RAM.
        IRONIC_AGENT_IMAGE_DOWNLOAD_SOURCE: http
        IRONIC_VM_SPECS_RAM: 3072
      devstack_services:
        # Since we're using streaming, try non-swift backends.
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
      configure_instance_user: metalsmith
      metalsmith_netboot: false
      metalsmith_precreate_port: false
      metalsmith_partition_image: test-centos-partition
      metalsmith_whole_disk_image: test-centos-wholedisk
      metalsmith_swap_size: 1024
      metalsmith_traits: [CUSTOM_GOLD]

- job:
    name: metalsmith-integration-glance-netboot-cirros
    description: |
        Integration job using Glance as image source and direct deploy.
    parent: metalsmith-integration-base
    run: playbooks/integration/run.yaml
    vars:
      devstack_localrc:
        IRONIC_BOOT_MODE: bios
      metalsmith_netboot: true
      metalsmith_precreate_port: false

- job:
    name: metalsmith-integration-http-netboot-cirros
    description: |
        Integration job using HTTP as image source and direct deploy.
    parent: metalsmith-integration-base
    run: playbooks/integration/run.yaml
    vars:
      devstack_localrc:
        IRONIC_BOOT_MODE: bios
      metalsmith_netboot: true
      metalsmith_precreate_port: true
      metalsmith_use_http: true

- project:
    templates:
      - check-requirements
      - openstack-python3-yoga-jobs
      - openstack-cover-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - metalsmith-integration-glance-localboot-centos8-uefi
        - metalsmith-integration-glance-netboot-cirros
        - metalsmith-integration-http-netboot-cirros
    gate:
      jobs:
        - metalsmith-integration-glance-localboot-centos8-uefi
        - metalsmith-integration-glance-netboot-cirros
        - metalsmith-integration-http-netboot-cirros
