- job:
    name: metalsmith-integration-base
    description: |
        Base job for devstack-based metalsmith jobs.
    parent: devstack-minimal
    pre-run: playbooks/integration/pre.yaml
    post-run: playbooks/integration/post.yaml
    run: playbooks/integration/run.yaml
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^lower-constraints.txt$
      - ^metalsmith/test/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^test-requirements.txt$
      - ^tools/.*$
      - ^tox.ini$
    timeout: 5400
    required-projects:
      - openstack/keystone
      - openstack/neutron
      - openstack/glance
      - openstack/swift
      - openstack/ironic
      - openstack/metalsmith
    vars:
      ironic_bm_logs: /opt/stack/logs/ironic-bm-logs
      devstack_services:
        dstat: true
        etcd3: true
        mysql: true
        peakmem_tracker: true
        rabbit: true
        tls-proxy: true
        # Keystone services
        key: true
        # Glance services
        g-api: true
        g-reg: true
        # Nova services
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # Neutron services
        q-agt: false
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
        q-svc: false
        neutron-api: true
        neutron-agent: true
        neutron-dhcp: true
        neutron-l3: true
        neutron-metadata-agent: true
        neutron-metering: true
        # Swift services
        s-account: true
        s-container: true
        s-object: true
        s-proxy: true
        # Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        # Ceilometer services
        ceilometer-acentral: False
        ceilometer-acompute: False
        ceilometer-alarm-evaluator: False
        ceilometer-alarm-notifier: False
        ceilometer-anotification: False
        ceilometer-api: False
        ceilometer-collector: False
        # Services we don't need.
        horizon: false
        tempest: false
      devstack_plugins:
        ironic: https://opendev.org/openstack/ironic
      devstack_localrc:
        IRONIC_BAREMETAL_BASIC_OPS: true
        IRONIC_BUILD_DEPLOY_RAMDISK: false
        IRONIC_DEFAULT_DEPLOY_INTERFACE: iscsi
        IRONIC_DEPLOY_DRIVER: ipmi
        IRONIC_RAMDISK_TYPE: tinyipa
        IRONIC_VM_COUNT: 1
        IRONIC_VM_LOG_DIR: /opt/stack/logs/ironic-bm-logs
        IRONIC_VM_SPECS_CPU: 2
        IRONIC_VM_SPECS_DISK: 10
        IRONIC_VM_SPECS_RAM: 1024
        SWIFT_ENABLE_TEMPURLS: true
        SWIFT_HASH: 54bd5642300c4b45-846f8636a70a07d2
        SWIFT_START_ALL_SERVICES: false
        SWIFT_TEMPURL_KEY: 54bd5642300c4b45846f8636a70a07d2
      centos_glance_initramds_image: test-centos-initramfs
      centos_glance_kernel_image: test-centos-kernel
      centos_glance_root_image: test-centos-partition
      centos_glance_whole_disk_image: test-centos-wholedisk
      centos_image_file: ~/CentOS-7-x86_64-GenericCloud.qcow2
      centos_image_name: CentOS-7-x86_64-GenericCloud
      centos_image_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2.xz
      centos_initramfs_file: ~/CentOS-7-x86_64-GenericCloud.initramfs
      centos_kernel_file: ~/CentOS-7-x86_64-GenericCloud.kernel
      centos_partition_file: ~/CentOS-7-x86_64-GenericCloud-root.qcow2
      metalsmith_root_size: 9

- job:
    name: metalsmith-integration-glance-localboot-centos7
    description: |
        Integration job using Glance as image source and CentOS7 with local boot.
    parent: metalsmith-integration-base
    pre-run: playbooks/integration/centos-image.yaml
    vars:
      configure_instance_user: metalsmith
      metalsmith_netboot: false
      metalsmith_precreate_port: false
      metalsmith_partition_image: test-centos-partition
      metalsmith_whole_disk_image: test-centos-wholedisk
      metalsmith_swap_size: 1024
      metalsmith_traits: [CUSTOM_GOLD]

- job:
    name: metalsmith-integration-glance-netboot-cirros-iscsi-py3
    description: |
        Integration job using Glance as image source and CirrOS with netboot.
    parent: metalsmith-integration-base
    vars:
      devstack_localrc:
        USE_PYTHON3: true
      metalsmith_netboot: true
      metalsmith_precreate_port: true
      metalsmith_python: python3

- job:
    name: metalsmith-integration-glance-netboot-cirros-direct
    description: |
        Integration job using Glance as image source and direct deploy.
    parent: metalsmith-integration-base
    run: playbooks/integration/run.yaml
    vars:
      metalsmith_netboot: true
      metalsmith_precreate_port: false
      devstack_localrc:
        IRONIC_DEFAULT_DEPLOY_INTERFACE: direct

- job:
    name: metalsmith-integration-http-netboot-cirros-direct-py3
    description: |
        Integration job using HTTP as image source and direct deploy.
    parent: metalsmith-integration-base
    run: playbooks/integration/run.yaml
    vars:
      metalsmith_netboot: true
      metalsmith_precreate_port: true
      metalsmith_python: python3
      metalsmith_use_http: true
      devstack_localrc:
        IRONIC_DEFAULT_DEPLOY_INTERFACE: direct
        USE_PYTHON3: true

- project:
    templates:
      - check-requirements
      - openstack-python-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - openstack-lower-constraints-jobs
      - openstack-cover-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - metalsmith-integration-glance-localboot-centos7
        - metalsmith-integration-glance-netboot-cirros-iscsi-py3
        - metalsmith-integration-glance-netboot-cirros-direct
        - metalsmith-integration-http-netboot-cirros-direct-py3
    gate:
      jobs:
        - metalsmith-integration-glance-localboot-centos7
        - metalsmith-integration-glance-netboot-cirros-iscsi-py3
        - metalsmith-integration-glance-netboot-cirros-direct
        - metalsmith-integration-http-netboot-cirros-direct-py3
