- job:
    name: metalsmith-integration-base
    description: |
        Base job for devstack-based metalsmith jobs.
    parent: devstack-minimal
    pre-run: playbooks/integration/pre.yaml
    post-run: playbooks/integration/post.yaml
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^lower-constraints.txt$
      - ^metalsmith/test/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^test-requirements.txt$
      - ^tools/.*$
      - ^tox.ini$
    timeout: 5400
    required-projects:
      - openstack/keystone
      - openstack/neutron
      - openstack/glance
      - openstack/ironic
      - openstack/metalsmith
    vars:
      ironic_bm_logs: /opt/stack/logs/ironic-bm-logs
      devstack_services:
        dstat: true
        etcd3: true
        mysql: true
        peakmem_tracker: true
        rabbit: true
        tls-proxy: true
        # Keystone services
        key: true
        # Glance services
        g-api: true
        g-reg: true
        # Nova services
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # Neutron services
        q-agt: false
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
        q-svc: false
        neutron-api: true
        neutron-agent: true
        neutron-dhcp: true
        neutron-l3: true
        neutron-metadata-agent: true
        neutron-metering: true
        # Swift services
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        # Ceilometer services
        ceilometer-acentral: False
        ceilometer-acompute: False
        ceilometer-alarm-evaluator: False
        ceilometer-alarm-notifier: False
        ceilometer-anotification: False
        ceilometer-api: False
        ceilometer-collector: False
        # Services we don't need.
        horizon: false
        tempest: false
      devstack_plugins:
        ironic: https://git.openstack.org/openstack/ironic
      devstack_localrc:
        IRONIC_BAREMETAL_BASIC_OPS: true
        IRONIC_BUILD_DEPLOY_RAMDISK: false
        IRONIC_DEPLOY_DRIVER: ipmi
        IRONIC_RAMDISK_TYPE: tinyipa
        IRONIC_VM_COUNT: 1
        IRONIC_VM_LOG_DIR: /opt/stack/logs/ironic-bm-logs
        IRONIC_VM_SPECS_CPU: 2
        IRONIC_VM_SPECS_DISK: 10
        IRONIC_VM_SPECS_RAM: 1024

- job:
    name: metalsmith-integration-glance
    description: |
        Integration job using Glance as image source.
    parent: metalsmith-integration-base
    pre-run: playbooks/integration/centos-image.yaml
    run: playbooks/integration/run.yaml
    vars:
      centos_image_name: CentOS-7-x86_64-GenericCloud
      centos_image_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2.xz
      centos_image_file: ~/CentOS-7-x86_64-GenericCloud.qcow2
      centos_kernel_file: ~/CentOS-7-x86_64-GenericCloud.kernel
      centos_initramfs_file: ~/CentOS-7-x86_64-GenericCloud.initramfs
      centos_partition_file: ~/CentOS-7-x86_64-GenericCloud-root.qcow2
      centos_glance_whole_disk_image: test-centos-wholedisk
      centos_glance_kernel_image: test-centos-kernel
      centos_glance_initramds_image: test-centos-initramfs
      centos_glance_root_image: test-centos-partition

- project:
    templates:
      - docs-on-readthedocs
    vars:
      rtd_webhook_id: '37378'
    check:
      jobs:
        - openstack-tox-lower-constraints
        - metalsmith-integration-glance
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - metalsmith-integration-glance
