---
- hosts: all
  roles:
    - run-devstack

  tasks:
    - set_fact:
        metalsmith_src_dir: '{{ ansible_user_dir }}/src/opendev.org/openstack'

    # https://github.com/git/git/commit/8959555cee7ec045958f9b6dd62e541affb7e7d9
    - name: Mark the metalsmith as safe for git
      command: git config --global --add safe.directory "{{ metalsmith_src_dir }}/metalsmith"
      become: true

    - name: Install requirements for metalsmith
      pip:
        requirements: "{{ metalsmith_src_dir }}/metalsmith/requirements.txt"
        extra_args: -c {{ metalsmith_src_dir }}/requirements/upper-constraints.txt
      become: true
      environment:
        # NOTE(dtantsur): https://github.com/pypa/setuptools/issues/2353
        SETUPTOOLS_USE_DISTUTILS: stdlib
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Install metalsmith
      pip:
        name: "{{ metalsmith_src_dir }}/metalsmith"
        editable: true
      become: true
      environment:
        SETUPTOOLS_USE_DISTUTILS: stdlib
      vars:
        ansible_python_interpreter: /usr/bin/python3
