- hosts: all
  environment:
    OS_CLOUD: devstack-admin

  tasks:
    - include: ssh-key.yaml

    - include: cirros-image.yaml
      when: metalsmith_whole_disk_image is not defined

    - name: Test a partition image
      include: exercise.yaml
      vars:
        image: "{{ metalsmith_partition_image }}"
        precreate_port: false

    - name: Test a whole-disk image
      include: exercise.yaml
      vars:
        image: "{{ metalsmith_whole_disk_image }}"
        precreate_port: false
