- hosts: all
  environment:
    OS_CLOUD: devstack-admin

  tasks:
    - include: ssh-key.yaml

    - name: Find Cirros UEC image
      shell: |
        openstack image list -f value -c ID -c Name \
          | awk '/cirros.*uec/ { print $1; exit 0; }'
      register: cirros_uec_image_result

    - name: Find Cirros disk image
      shell: |
        openstack image list -f value -c ID -c Name \
          | awk '/cirros.*disk/ { print $1; exit 0; }'
      register: cirros_disk_image_result

    - name: Check that Cirros UEC image was found
      fail:
        msg: No Cirros UEC image found
      when: cirros_uec_image_result.stdout == ""

    - name: Check that Cirros disk image was found
      fail:
        msg: No Cirros disk image found
      when: cirros_disk_image_result.stdout == ""

    - include: exercise.yaml
      vars:
        image: "{{ cirros_uec_image_result.stdout }}"
        precreate_port: false

    - include: exercise.yaml
      vars:
        image: "{{ cirros_disk_image_result.stdout }}"
        precreate_port: true
