---

- name: Build instance defaults
  metalsmith_deployment_defaults:
    instances: "{{ metalsmith_instances }}"
    defaults:
      candidates: "{{ metalsmith_candidates }}"
      capabilities: "{{ metalsmith_capabilities }}"
      conductor_group: "{{ metalsmith_conductor_group }}"
      extra_args: "{{ metalsmith_extra_args }}"
      image: "{{ metalsmith_image }}"
      image_checksum: "{{ metalsmith_image_checksum }}"
      image_kernel: "{{ metalsmith_image_kernel }}"
      image_ramdisk: "{{ metalsmith_image_ramdisk }}"
      netboot: "{{ metalsmith_netboot }}"
      nics: "{{ metalsmith_nics }}"
      resource_class: "{{ metalsmith_resource_class }}"
      root_size: "{{ metalsmith_root_size }}"
      ssh_public_keys: "{{ metalsmith_ssh_public_keys }}"
      swap_size: "{{ metalsmith_swap_size }}"
      traits: "{{ metalsmith_traits }}"
      user_name: "{{ metalsmith_user_name }}"
  register: instances

- name: Show instances data
  debug:
    msg: "{{ instances.instances | to_yaml }}"
  when: metalsmith_debug|bool

- name: Provision instances
  metalsmith_instances:
    instances: "{{ instances.instances }}"
    state: "{{ metalsmith_state }}"
    wait: true
    timeout: "{{ metalsmith_provisioning_timeout }}"
    log_level: "{{ 'debug' if metalsmith_debug|bool else 'info' }}"
  register: baremetal_reserved

- name: Metalsmith log for reserve instances
  debug:
    var: baremetal_reserved.logging
  when: metalsmith_debug|bool
